from src.recipe_generator.llm import get_text_model


def summarize_recipes(recipes: list) -> str:

    llm = get_text_model()

    recipe_details = []

    for index, recipe in enumerate(recipes, start=1):

        recipe_details.append(
            f"""
Chef {index}
Recipe: {recipe.name}
Description: {recipe.description}
Servings: {recipe.servings}
Cooking Time: {recipe.cooking_time_minutes} minutes

Ingredients:
{chr(10).join(
    f"- {i.quantity} {i.name}"
    for i in recipe.ingredients
)}

Instructions:
{chr(10).join(
    f"{n}. {instruction}"
    for n, instruction in enumerate(recipe.instructions, start=1)
)}
"""
        )

    prompt = f"""
You are the Recipe Summary Chef.

Your task is ONLY to summarize all recipes generated by the
different chefs.

Do NOT recommend a recipe.
Do NOT select a winner.
Do NOT rank the recipes.
Do NOT say which recipe is best.

Provide a neutral summary of EVERY chef's recipe.

For each chef include:
- Recipe name
- Overall approach/style
- Main ingredients
- Cooking time
- Servings
- Important characteristics

At the end, provide a neutral comparison describing how
the recipes differ from each other.

Recipes:

{"".join(recipe_details)}
"""

    response = llm.invoke(prompt)

    return response.content